# Generated by Django 4.2.6 on 2024-06-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_pan_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pan_card',
        ),
    ]
