# Generated by Django 4.2.6 on 2024-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_customuser_pancard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
