# Generated by Django 4.2.6 on 2024-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cart_products_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
