# Generated by Django 4.2.13 on 2024-07-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
