# Generated by Django 4.2.13 on 2024-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('road', 'Road'), ('airline', 'Airline'), ('ship', 'Ship')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
