# Generated by Django 4.2.13 on 2024-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_estimated_delivery_date_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
