# Generated by Django 4.2.13 on 2024-07-05 16:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
