# Generated by Django 4.2.13 on 2024-07-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_id',
        ),
    ]
